# Generated by Django 4.2.6 on 2023-12-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="название категории профессии",
                        max_length=100,
                        verbose_name="категория",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="описание категории",
                        verbose_name="описание",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="опубликована категория/профессия или нет",
                        verbose_name="опубликовано",
                    ),
                ),
                (
                    "link_to_professions",
                    models.URLField(
                        blank=True,
                        help_text="ссылка на весь список профессий в данной категории",
                        max_length=250,
                        verbose_name="ссылка",
                    ),
                ),
                (
                    "num_of_professions",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="количество профессий в категории",
                        verbose_name="количество профессий",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
    ]
