# Generated by Django 4.2.6 on 2023-12-10 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessionsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="название категории профессии",
                        max_length=100,
                        verbose_name="категория",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="описание категории",
                        verbose_name="описание",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="опубликована категория/профессия или нет",
                        verbose_name="опубликовано",
                    ),
                ),
                (
                    "wage",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="заработная плата",
                        verbose_name="заработная плата",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="к какой категории относится профессия",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.categoriesmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "профессия",
                "verbose_name_plural": "профессии",
                "ordering": ["name"],
            },
        ),
    ]
