# Generated by Django 4.2.6 on 2023-12-03 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
        ("professions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="professionsmodel",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="опубликована категория/профессия или нет",
                verbose_name="опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="professionsmodel",
            name="category",
            field=models.ForeignKey(
                help_text="к какой категории относится профессия",
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.categoriesmodel",
            ),
        ),
        migrations.AlterField(
            model_name="professionsmodel",
            name="description",
            field=models.TextField(
                blank=True, help_text="описание категории", verbose_name="описание"
            ),
        ),
        migrations.AlterField(
            model_name="professionsmodel",
            name="name",
            field=models.CharField(
                help_text="название категории профессии",
                max_length=100,
                verbose_name="категория",
            ),
        ),
        migrations.AlterField(
            model_name="professionsmodel",
            name="wage",
            field=models.CharField(
                help_text="заработная плата",
                max_length=100,
                verbose_name="заработная плата",
            ),
        ),
        migrations.DeleteModel(
            name="CategoriesModel",
        ),
    ]
