# Generated by Django 4.2.6 on 2023-12-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("professions", "0003_alter_professionsmodel_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professionsmodel",
            name="wage",
            field=models.PositiveIntegerField(
                default=0, help_text="заработная плата", verbose_name="заработная плата"
            ),
        ),
    ]
