name: Run Tests

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run flake8
        run: |
          pip3 install requirements/test.txt
          flake8 –config=setup.cfg